/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.dblibreria;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public class Articulo extends javax.swing.JFrame {
    connection Ca=new connection();
    Connection li=Ca.conexiondb();
    PreparedStatement ps=null;
    ResultSet re=null;
    /**
     * Creates new form Articulo
     */
    public Articulo() {
        initComponents();
         Cargartablas();
    }
public void Cargartablas(){
        DefaultTableModel tabla=new DefaultTableModel();
        tabla.addColumn("Id");
        tabla.addColumn("Titulo");
        tabla.addColumn("Autor");
        tabla.addColumn("Editorial");
        tabla.addColumn("Precio"); 

        
        
       
        
        tablaconsulta.setModel(tabla);
        String datos[]=new String[5];
        try{
            ps=li.prepareStatement("SELECT*FROM articulo");
            re=ps.executeQuery();
            while(re.next()){
                datos[0]=re.getString(1);
                datos[1]=re.getString(2);
                datos[2]=re.getString(3);
                datos[3]=re.getString(4);
                datos[4]=re.getString(5);
                 
            
                
                
                tabla.addRow(datos);
                
            }
        }
        catch (Exception e){
            System.out.print(e);
            
        }
}
public void Registrar(){
    try{
    
    ps=li.prepareStatement("INSERT INTO articulo(id_art,tit_art,aut_art,edi_art,prec_art) values (?,?,?,?,?)");
    ps.setInt(1,Integer.parseInt(jTextCodigo.getText()));
    ps.setString(2,jTexTITULO.getText());
    ps.setString(3,jTextAUTOR.getText());
    ps.setString(4,jTextEDITOR.getText());
    ps.setString(5,jTextPRECIO.getText());


    
  
    
   
    ps.executeUpdate();
        JOptionPane.showMessageDialog(null,"Datos guardados");
    }
    catch (Exception e){
    System.out.print("es " + e);
    }
}
    public void Eliminar(String dat){
        try{
        ps=li.prepareStatement("DELETE FROM articulo where  id_art='"+dat+"' ");
        ps.executeUpdate();
        JOptionPane.showMessageDialog(null,"Datos eliminados");
        }
            catch(Exception e){
                    System.out.print(e);
                    }
        }
public void Modificar(String  id,String tit,String aut,String edi,String prec){
        try{
            ps=li.prepareStatement("UPDATE articulo SET  tit_art='"+tit+"',aut_art='" +aut+"',edi_art='" +edi+"',prec_art='" +prec+"' where id_art='"+id +"' ");
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"Datos Modificados");
        }
        catch(Exception e){
            
            System.out.print( e);
        }
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaconsulta = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextEDITOR = new javax.swing.JTextField();
        jTexTITULO = new javax.swing.JTextField();
        jTextPRECIO = new javax.swing.JTextField();
        jTextAUTOR = new javax.swing.JTextField();
        jBuModifi = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaconsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaconsulta);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 850, 190));

        jButton7.setText("Registrar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 186, -1, -1));

        jButton6.setText("Eliminar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 186, -1, -1));

        jButton5.setText("Limpiar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 186, -1, -1));

        jButton1.setText("ATRAS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 186, -1, -1));
        getContentPane().add(jTextCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 81, 28));

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel1.setText("Codigo ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 36, -1, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel2.setText("Titulo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 36, -1, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel3.setText("Autor");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 36, -1, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel4.setText("Editorial");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel5.setText("Precio");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 100, -1, -1));
        getContentPane().add(jTextEDITOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 81, 28));
        getContentPane().add(jTexTITULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 29, 81, 28));

        jTextPRECIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPRECIOActionPerformed(evt);
            }
        });
        getContentPane().add(jTextPRECIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 93, 81, 28));
        getContentPane().add(jTextAUTOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 29, 81, 28));

        jBuModifi.setText("Modificar");
        jBuModifi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuModifiActionPerformed(evt);
            }
        });
        getContentPane().add(jBuModifi, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 186, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/articulo.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Registrar();
        Cargartablas();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String dat=jTextCodigo.getText();
        Eliminar(dat);
        Cargartablas();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jTextCodigo.setText(null);
        jTexTITULO.setText(null);
        jTextAUTOR.setText(null);
        jTextEDITOR.setText(null);
        jTextPRECIO.setText(null);
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MenuL m=new MenuL();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextPRECIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPRECIOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPRECIOActionPerformed

    private void jBuModifiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuModifiActionPerformed
      String id,tit,aut,edi,prec;

        id=jTextCodigo.getText();

        tit=jTexTITULO.getText();
        aut=jTextAUTOR.getText();
        edi=jTextEDITOR.getText();
        prec=jTextPRECIO.getText();
      

        Modificar(id, tit, aut, edi, prec);
        Cargartablas();
    }//GEN-LAST:event_jBuModifiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Articulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Articulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Articulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Articulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Articulo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBuModifi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTexTITULO;
    private javax.swing.JTextField jTextAUTOR;
    private javax.swing.JTextField jTextCodigo;
    private javax.swing.JTextField jTextEDITOR;
    private javax.swing.JTextField jTextPRECIO;
    private javax.swing.JTable tablaconsulta;
    // End of variables declaration//GEN-END:variables
}
