/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.dblibreria;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public class articuloxpedido extends javax.swing.JFrame {
  connection Ca=new connection();
    Connection li=Ca.conexiondb();
    PreparedStatement ps=null;
    ResultSet re=null;
    /**
     * Creates new form articuloxpedido
     */
    public articuloxpedido() {
        initComponents();
        Cargartablas();
        Cargarcombox();
    }
public void Cargartablas(){
        DefaultTableModel tabla=new DefaultTableModel();
        tabla.addColumn("Id pedido");
        tabla.addColumn("Id articulo");
        tabla.addColumn("Cantidad articulo");
        tabla.addColumn("Valor venta");

        
        
       
        
        tablaconsulta.setModel(tabla);
        String datos[]=new String[5];
        try{
            ps=li.prepareStatement("SELECT*FROM articuloxpedido");
            re=ps.executeQuery();
            while(re.next()){
                datos[0]=re.getString(1);
                datos[1]=re.getString(2);
                datos[2]=re.getString(3);
                datos[3]=re.getString(4);
                 
            
                
                
                tabla.addRow(datos);
                
            }
        }
        catch (Exception e){
            System.out.print(e);
            
        }
}
public void Registrar(){
    try{
    
    ps=li.prepareStatement("INSERT INTO articuloxpedido(id_ped_artped,id_art_artped,can_art_artped,val_ven_art_artped) values (?,?,?,?)");
    ps.setString(1,jComboBox1.getSelectedItem().toString());
    ps.setString(2,jComboBox2.getSelectedItem().toString());
    ps.setString(3,jTexCANTA.getText());
    ps.setString(4,jTextVAL.getText());



    
  
    
   
    ps.executeUpdate();
        JOptionPane.showMessageDialog(null,"Datos guardados");
    }
    catch (Exception e){
    System.out.print("es " + e);
    }
}
    public void Eliminar(String dat){
        try{
        ps=li.prepareStatement("DELETE FROM articuloxpedido where  id_ped_artped='"+dat+"' ");
        ps.executeUpdate();
        JOptionPane.showMessageDialog(null,"Datos eliminados");
        }
            catch(Exception e){
                    System.out.print(e);
                    }
        }

public void Cargarcombox(){
    try{
        jComboBox1.removeAll();
        jComboBox1.addItem("Seleccione Codigo");
        ps=li.prepareStatement("SELECT id_ped FROM  pedido");
        re=ps.executeQuery();
        while(re.next()){
            String aux=re.getString("id_ped");
            this.jComboBox1.addItem(aux);
        }
    }
    catch(Exception e){
        
        
    }
    try{
        jComboBox2.removeAll();
        jComboBox2.addItem("Seleccione Codigo");
        ps=li.prepareStatement("SELECT id_art FROM  articulo");
        re=ps.executeQuery();
        while(re.next()){
            String aux=re.getString("id_art");
            this.jComboBox2.addItem(aux);
        }
    }
    catch(Exception e){
        
        
    }
}
public void Modificar(String  idp,String ida,String can,String val){
        try{
            ps=li.prepareStatement("UPDATE articulo SET  can_art_artped='" +can+"',val_ven_art_artped='" +val+"' where id_ped_artped='"+idp +"' and id_art_artped='" +ida+"' ");
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"Datos Modificados");
        }
        catch(Exception e){
            
            System.out.print( e);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaconsulta = new javax.swing.JTable();
        jBuRE = new javax.swing.JButton();
        jbEL = new javax.swing.JButton();
        jBuLIM = new javax.swing.JButton();
        jBATRAS = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTexCANTA = new javax.swing.JTextField();
        jTextVAL = new javax.swing.JTextField();
        jBuModifi2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaconsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaconsulta);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 252, 747, 206));

        jBuRE.setText("Registrar");
        jBuRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuREActionPerformed(evt);
            }
        });
        getContentPane().add(jBuRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 202, -1, -1));

        jbEL.setText("Eliminar");
        jbEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbELActionPerformed(evt);
            }
        });
        getContentPane().add(jbEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 202, -1, -1));

        jBuLIM.setText("Limpiar");
        jBuLIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuLIMActionPerformed(evt);
            }
        });
        getContentPane().add(jBuLIM, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 202, -1, -1));

        jBATRAS.setText("ATRAS");
        jBATRAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBATRASActionPerformed(evt);
            }
        });
        getContentPane().add(jBATRAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 202, -1, -1));

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel1.setText("Codigo Pedido");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 33, -1, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel2.setText("Codigo Articulo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel3.setText("Cantidad de articulos ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 97, -1, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel4.setText("Valor de  la venta");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 58, -1));

        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 70, -1));
        getContentPane().add(jTexCANTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 70, 20));
        getContentPane().add(jTextVAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 72, -1));

        jBuModifi2.setText("Modificar");
        jBuModifi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuModifi2ActionPerformed(evt);
            }
        });
        getContentPane().add(jBuModifi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 202, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arxped.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 800, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBuREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuREActionPerformed
        Registrar();
        Cargartablas();
    }//GEN-LAST:event_jBuREActionPerformed

    private void jbELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbELActionPerformed
        String dat=jComboBox1.getActionCommand();
        Eliminar(dat);
        Cargartablas();
    }//GEN-LAST:event_jbELActionPerformed

    private void jBuLIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuLIMActionPerformed
        jComboBox1.removeAllItems();
        jComboBox2.removeAllItems();
        jTexCANTA.setText(null);
        jTextVAL.setText(null);

    }//GEN-LAST:event_jBuLIMActionPerformed

    private void jBATRASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBATRASActionPerformed
        MenuL m=new MenuL();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBATRASActionPerformed

    private void jBuModifi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuModifi2ActionPerformed
        String idp,ida,can,val;

        idp=jComboBox1.getSelectedItem().toString();

        ida=jComboBox2.getSelectedItem().toString();
        can=jTexCANTA.getText();
        val=jTextVAL.getText();
        

        Modificar(idp, ida, can, val);
        Cargartablas();
    }//GEN-LAST:event_jBuModifi2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(articuloxpedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(articuloxpedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(articuloxpedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(articuloxpedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new articuloxpedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBATRAS;
    private javax.swing.JButton jBuLIM;
    private javax.swing.JButton jBuModifi2;
    private javax.swing.JButton jBuRE;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTexCANTA;
    private javax.swing.JTextField jTextVAL;
    private javax.swing.JButton jbEL;
    private javax.swing.JTable tablaconsulta;
    // End of variables declaration//GEN-END:variables
}
