/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.dblibreria;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public class Pedido extends javax.swing.JFrame {
    connection Ca=new connection();
    Connection li=Ca.conexiondb();
    PreparedStatement ps=null;
    ResultSet re=null;
    /**
     * Creates new form Pedido
     */
    public Pedido() {
        initComponents();
        Cargartablas();
        Cargarcombox();
    }

public void Cargartablas(){
        DefaultTableModel tabla=new DefaultTableModel();
        tabla.addColumn("Id pedido");
        tabla.addColumn("Documento Cliente");
        tabla.addColumn("Fecha del pedido");
        tabla.addColumn("valor pedido");
        

        
        
       
        
        tablaconsulta.setModel(tabla);
        String datos[]=new String[5];
        try{
            ps=li.prepareStatement("SELECT*FROM pedido");
            re=ps.executeQuery();
            while(re.next()){
                datos[0]=re.getString(1);
                datos[1]=re.getString(2);
                datos[2]=re.getString(3);
                datos[3]=re.getString(4);
               
                 
            
                
                
                tabla.addRow(datos);
                
            }
        }
        catch (Exception e){
            System.out.print(e);
            
        }
}
public void Registrar(){
    try{
    
    ps=li.prepareStatement("INSERT INTO pedido(id_ped,id_cli_ped,fec_ped,val_ped) values (?,?,?,?)");
    ps.setInt(1,Integer.parseInt(jTexCODIGOP.getText()));
    ps.setString(2,jComboBox1.getSelectedItem().toString());
    ps.setString(3,jTexFECHP.getText());
    ps.setString(4,jTextVAl.getText());



    
  
    
   
    ps.executeUpdate();
        JOptionPane.showMessageDialog(null,"Datos guardados");
    }
    catch (Exception e){
    System.out.print("es " + e);
    }
}
    public void Eliminar(String dat){
        try{
        ps=li.prepareStatement("DELETE FROM pedido where  id_ped='"+dat+"' ");
        ps.executeUpdate();
        JOptionPane.showMessageDialog(null,"Datos eliminados");
        }
            catch(Exception e){
                    System.out.print(e);
                    }
        }

public void Cargarcombox(){
    try{
        jComboBox1.removeAll();
        jComboBox1.addItem("Seleccione Codigo");
        ps=li.prepareStatement("SELECT id_cli FROM  cliente");
        re=ps.executeQuery();
        while(re.next()){
            String aux=re.getString("id_cli");
            this.jComboBox1.addItem(aux);
        }
    }
    catch(Exception e){
        
        
    }
   
}


    public void Modificar(String  iC,String fec,String val,String id){
        try{
            ps=li.prepareStatement("UPDATE pedido SET id_cli_ped='"+iC +"' ,fec_ped='"+ fec+"',val_ped='"+ val+ "'  where id_ped='" +id+"' ");
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"Datos Modificados");
        }
        catch(Exception e){
            
            System.out.print( e);
        }
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaconsulta = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTexCODIGOP = new javax.swing.JTextField();
        jTexFECHP = new javax.swing.JTextField();
        jTextVAl = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jBuRE = new javax.swing.JButton();
        jbEL = new javax.swing.JButton();
        jBuLIM = new javax.swing.JButton();
        jBATRAS = new javax.swing.JButton();
        jBuModifi = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaconsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaconsulta);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 231, 830, 347));

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel1.setText("Codigo pedido");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 41, -1, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fecha de pedido");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 41, -1, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel3.setText("Codigo Cliente");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 122, -1, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Valor ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 122, -1, -1));
        getContentPane().add(jTexCODIGOP, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 127, 35));
        getContentPane().add(jTexFECHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, 127, 35));
        getContentPane().add(jTextVAl, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 127, 35));

        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 125, 36));

        jBuRE.setText("Registrar");
        jBuRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuREActionPerformed(evt);
            }
        });
        getContentPane().add(jBuRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 197, -1, -1));

        jbEL.setText("Eliminar");
        jbEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbELActionPerformed(evt);
            }
        });
        getContentPane().add(jbEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 197, -1, -1));

        jBuLIM.setText("Limpiar");
        jBuLIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuLIMActionPerformed(evt);
            }
        });
        getContentPane().add(jBuLIM, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 197, -1, -1));

        jBATRAS.setText("ATRAS");
        jBATRAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBATRASActionPerformed(evt);
            }
        });
        getContentPane().add(jBATRAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(723, 197, -1, -1));

        jBuModifi.setText("Modificar");
        jBuModifi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuModifiActionPerformed(evt);
            }
        });
        getContentPane().add(jBuModifi, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 197, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pedido.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-360, 0, 1250, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBuREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuREActionPerformed
        Registrar();
        Cargartablas();
    }//GEN-LAST:event_jBuREActionPerformed

    private void jbELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbELActionPerformed
        String dat=jTexCODIGOP.getText();
        Eliminar(dat);
        Cargartablas();
    }//GEN-LAST:event_jbELActionPerformed

    private void jBuLIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuLIMActionPerformed
        jTexCODIGOP.setText(null);
        jComboBox1.removeAllItems();
        jTexFECHP.setText(null);
        jTextVAl.setText(null);
    

    }//GEN-LAST:event_jBuLIMActionPerformed

    private void jBATRASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBATRASActionPerformed
        MenuL m=new MenuL();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBATRASActionPerformed

    private void jBuModifiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuModifiActionPerformed
        String  iC,fec,val,id;
        iC=jComboBox1.getSelectedItem().toString();
        fec=jTexFECHP.getText();
        val=jTextVAl.getText();
        id=jTexCODIGOP.getText();

        Modificar(iC, fec, val, id);
        Cargartablas();
    }//GEN-LAST:event_jBuModifiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBATRAS;
    private javax.swing.JButton jBuLIM;
    private javax.swing.JButton jBuModifi;
    private javax.swing.JButton jBuRE;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTexCODIGOP;
    private javax.swing.JTextField jTexFECHP;
    private javax.swing.JTextField jTextVAl;
    private javax.swing.JButton jbEL;
    private javax.swing.JTable tablaconsulta;
    // End of variables declaration//GEN-END:variables
}
